import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

interface SlackReactionData {
  ok: boolean
  items: {
    type: string
    channel: string
    message: {
      type: string
      subtype: string
      text: string
      ts: string
      username: string
      icons: {
        image_36: string
        image_48: string
        image_72: string
      }
      bot_id: string
      attachments: {
        from_url: string
        ts: number
        id: number
        original_url: string
        fallback: string
        text: string
        pretext: string
        title: string
        title_link: string
        author_name: string
        author_link: string
        author_icon: string
        author_subname: string
        service_name: string
        service_url: string
        mrkdwn_in: string[],
        footer: string[],
        footer_icon: string
      }[]
      reactions: {
        name: string
        users: string[]
        count: number
      }[]
      permalink: string
    }
  }[]
  response_metadata: {
    next_cursor: string
  }
}

export async function getStaticProps() {
  const res = await fetch(`https://slack.com/api/reactions.list?user=${process.env.USER_ID}&pretty=1`, {
    method: 'GET',
    headers: {
      Authorization: `Bearer ${process.env.BOT_USER_OAUTH_TOKEN}`,
    }
  })

  const reactionList: SlackReactionData = await res.json()
  console.log(reactionList.items[0].message.attachments)
  console.log(reactionList.items[0].message.reactions)
  return {
    props: {}
  }
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
